//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.31 at 02:36:29 PM GMT 
//


package uk.org.whitecottage.ea.gnosis.jaxb.framework;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}organisation" minOccurs="0"/>
 *         &lt;element ref="{}businessProcesses" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organisation",
    "businessProcesses"
})
@XmlRootElement(name = "businessOperatingModel")
public class BusinessOperatingModel {

    protected Organisation organisation;
    protected BusinessProcesses businessProcesses;

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link Organisation }
     *     
     */
    public Organisation getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organisation }
     *     
     */
    public void setOrganisation(Organisation value) {
        this.organisation = value;
    }

    /**
     * Gets the value of the businessProcesses property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessProcesses }
     *     
     */
    public BusinessProcesses getBusinessProcesses() {
        return businessProcesses;
    }

    /**
     * Sets the value of the businessProcesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessProcesses }
     *     
     */
    public void setBusinessProcesses(BusinessProcesses value) {
        this.businessProcesses = value;
    }

}
