//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.31 at 02:36:29 PM GMT 
//


package uk.org.whitecottage.ea.gnosis.jaxb.framework;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}businessContext"/>
 *         &lt;element ref="{}businessOperatingModel"/>
 *         &lt;element ref="{}businessApplications"/>
 *         &lt;element ref="{}commonServices"/>
 *         &lt;element ref="{}infrastructure"/>
 *         &lt;element ref="{}valueChain"/>
 *         &lt;element ref="{}recycleBin" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "businessContext",
    "businessOperatingModel",
    "businessApplications",
    "commonServices",
    "infrastructure",
    "valueChain",
    "recycleBin"
})
@XmlRootElement(name = "framework")
public class Framework {

    @XmlElement(required = true)
    protected Object businessContext;
    @XmlElement(required = true)
    protected BusinessOperatingModel businessOperatingModel;
    @XmlElement(required = true)
    protected BusinessApplications businessApplications;
    @XmlElement(required = true)
    protected CommonServices commonServices;
    @XmlElement(required = true)
    protected Infrastructure infrastructure;
    @XmlElement(required = true)
    protected ValueChain valueChain;
    protected RecycleBin recycleBin;

    /**
     * Gets the value of the businessContext property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBusinessContext() {
        return businessContext;
    }

    /**
     * Sets the value of the businessContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBusinessContext(Object value) {
        this.businessContext = value;
    }

    /**
     * Gets the value of the businessOperatingModel property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessOperatingModel }
     *     
     */
    public BusinessOperatingModel getBusinessOperatingModel() {
        return businessOperatingModel;
    }

    /**
     * Sets the value of the businessOperatingModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessOperatingModel }
     *     
     */
    public void setBusinessOperatingModel(BusinessOperatingModel value) {
        this.businessOperatingModel = value;
    }

    /**
     * Gets the value of the businessApplications property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessApplications }
     *     
     */
    public BusinessApplications getBusinessApplications() {
        return businessApplications;
    }

    /**
     * Sets the value of the businessApplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessApplications }
     *     
     */
    public void setBusinessApplications(BusinessApplications value) {
        this.businessApplications = value;
    }

    /**
     * Gets the value of the commonServices property.
     * 
     * @return
     *     possible object is
     *     {@link CommonServices }
     *     
     */
    public CommonServices getCommonServices() {
        return commonServices;
    }

    /**
     * Sets the value of the commonServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonServices }
     *     
     */
    public void setCommonServices(CommonServices value) {
        this.commonServices = value;
    }

    /**
     * Gets the value of the infrastructure property.
     * 
     * @return
     *     possible object is
     *     {@link Infrastructure }
     *     
     */
    public Infrastructure getInfrastructure() {
        return infrastructure;
    }

    /**
     * Sets the value of the infrastructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Infrastructure }
     *     
     */
    public void setInfrastructure(Infrastructure value) {
        this.infrastructure = value;
    }

    /**
     * Gets the value of the valueChain property.
     * 
     * @return
     *     possible object is
     *     {@link ValueChain }
     *     
     */
    public ValueChain getValueChain() {
        return valueChain;
    }

    /**
     * Sets the value of the valueChain property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueChain }
     *     
     */
    public void setValueChain(ValueChain value) {
        this.valueChain = value;
    }

    /**
     * Gets the value of the recycleBin property.
     * 
     * @return
     *     possible object is
     *     {@link RecycleBin }
     *     
     */
    public RecycleBin getRecycleBin() {
        return recycleBin;
    }

    /**
     * Sets the value of the recycleBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecycleBin }
     *     
     */
    public void setRecycleBin(RecycleBin value) {
        this.recycleBin = value;
    }

}
