//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.31 at 02:36:29 PM GMT 
//


package uk.org.whitecottage.ea.gnosis.jaxb.framework;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}technologyDomain"/>
 *         &lt;element ref="{}capability"/>
 *         &lt;element ref="{}primaryActivity"/>
 *         &lt;element ref="{}supportActivity"/>
 *         &lt;element ref="{}processDomain"/>
 *         &lt;element ref="{}process"/>
 *         &lt;element ref="{}processComponent"/>
 *         &lt;element ref="{}processFlow"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "technologyDomainOrCapabilityOrPrimaryActivity"
})
@XmlRootElement(name = "recycleBin")
public class RecycleBin {

    @XmlElements({
        @XmlElement(name = "technologyDomain", type = TechnologyDomain.class),
        @XmlElement(name = "capability", type = Capability.class),
        @XmlElement(name = "primaryActivity", type = PrimaryActivity.class),
        @XmlElement(name = "supportActivity", type = SupportActivity.class),
        @XmlElement(name = "processDomain", type = ProcessDomain.class),
        @XmlElement(name = "process", type = Process.class),
        @XmlElement(name = "processComponent", type = ProcessComponent.class),
        @XmlElement(name = "processFlow", type = ProcessFlow.class)
    })
    protected List<Object> technologyDomainOrCapabilityOrPrimaryActivity;

    /**
     * Gets the value of the technologyDomainOrCapabilityOrPrimaryActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technologyDomainOrCapabilityOrPrimaryActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnologyDomainOrCapabilityOrPrimaryActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TechnologyDomain }
     * {@link Capability }
     * {@link PrimaryActivity }
     * {@link SupportActivity }
     * {@link ProcessDomain }
     * {@link Process }
     * {@link ProcessComponent }
     * {@link ProcessFlow }
     * 
     * 
     */
    public List<Object> getTechnologyDomainOrCapabilityOrPrimaryActivity() {
        if (technologyDomainOrCapabilityOrPrimaryActivity == null) {
            technologyDomainOrCapabilityOrPrimaryActivity = new ArrayList<Object>();
        }
        return this.technologyDomainOrCapabilityOrPrimaryActivity;
    }

}
