//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.31 at 11:53:00 AM BST 
//


package uk.org.whitecottage.ea.gnosis.jaxb.framework;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{}technologyDomain"/&gt;
 *         &lt;element ref="{}capability"/&gt;
 *         &lt;element ref="{}activity"/&gt;
 *         &lt;element ref="{}ecosystem"/&gt;
 *         &lt;element ref="{}capabilityInstance"/&gt;
 *         &lt;element ref="{}processDomain"/&gt;
 *         &lt;element ref="{}process"/&gt;
 *         &lt;element ref="{}processComponent"/&gt;
 *         &lt;element ref="{}processFlow"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "technologyDomainOrCapabilityOrActivity"
})
@XmlRootElement(name = "recycleBin")
public class RecycleBin {

    @XmlElements({
        @XmlElement(name = "technologyDomain", type = TechnologyDomain.class),
        @XmlElement(name = "capability", type = Capability.class),
        @XmlElement(name = "activity", type = Activity.class),
        @XmlElement(name = "ecosystem", type = Ecosystem.class),
        @XmlElement(name = "capabilityInstance", type = CapabilityInstance.class),
        @XmlElement(name = "processDomain", type = ProcessDomain.class),
        @XmlElement(name = "process", type = Process.class),
        @XmlElement(name = "processComponent", type = ProcessComponent.class),
        @XmlElement(name = "processFlow", type = ProcessFlow.class)
    })
    protected List<Object> technologyDomainOrCapabilityOrActivity;

    /**
     * Gets the value of the technologyDomainOrCapabilityOrActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technologyDomainOrCapabilityOrActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnologyDomainOrCapabilityOrActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TechnologyDomain }
     * {@link Capability }
     * {@link Activity }
     * {@link Ecosystem }
     * {@link CapabilityInstance }
     * {@link ProcessDomain }
     * {@link Process }
     * {@link ProcessComponent }
     * {@link ProcessFlow }
     * 
     * 
     */
    public List<Object> getTechnologyDomainOrCapabilityOrActivity() {
        if (technologyDomainOrCapabilityOrActivity == null) {
            technologyDomainOrCapabilityOrActivity = new ArrayList<Object>();
        }
        return this.technologyDomainOrCapabilityOrActivity;
    }

}
