//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.31 at 11:53:00 AM BST 
//


package uk.org.whitecottage.ea.gnosis.jaxb.framework;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}primaryActivities"/&gt;
 *         &lt;element ref="{}supportActivities"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primaryActivities",
    "supportActivities"
})
@XmlRootElement(name = "valueChain")
public class ValueChain {

    @XmlElement(required = true)
    protected PrimaryActivities primaryActivities;
    @XmlElement(required = true)
    protected SupportActivities supportActivities;

    /**
     * Gets the value of the primaryActivities property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryActivities }
     *     
     */
    public PrimaryActivities getPrimaryActivities() {
        return primaryActivities;
    }

    /**
     * Sets the value of the primaryActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryActivities }
     *     
     */
    public void setPrimaryActivities(PrimaryActivities value) {
        this.primaryActivities = value;
    }

    /**
     * Gets the value of the supportActivities property.
     * 
     * @return
     *     possible object is
     *     {@link SupportActivities }
     *     
     */
    public SupportActivities getSupportActivities() {
        return supportActivities;
    }

    /**
     * Sets the value of the supportActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportActivities }
     *     
     */
    public void setSupportActivities(SupportActivities value) {
        this.supportActivities = value;
    }

}
